name: Deploy to Databricks  

on:  
  workflow_dispatch: 

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  

    - name: Set up Python  
      uses: actions/setup-python@v2  
      with:  
        python-version: '3.x'  

    - name: Install Databricks CLI  
      run: pip install databricks-cli  

    - name: Configure Databricks CLI  
      run: |  
        databricks configure --token  
      env:  
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}  
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  

    - name: Deploy to Databricks  
      run: |  
        databricks workspace import-dir . /Workspace/Users/michael.lotfy@skillsoft.com/DatabricksProject  
        databricks apps deploy my-flask-app --source-code-path /Workspace/Users/michael.lotfy@skillsoft.com/DatabricksProject  
