name: Deploy to Databricks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI (new version)
      run: |
        curl -V
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        databricks -v

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN

    - name: Create workspace directory
      run: |
        databricks workspace mkdirs /Workspace/Users/michael.lotfy@skillsoft.com/newpr

    - name: Upload app.py to workspace
      run: |
        databricks workspace import --language PYTHON --format SOURCE app.py /Workspace/Users/michael.lotfy@skillsoft.com/newpr/app.py

    - name: Sync Databricks App
      run: |
        databricks apps sync --source-path /Workspace/Users/michael.lotfy@skillsoft.com/newpr
