name: Deploy to Databricks  
  
on:  
  workflow_dispatch:  
  
jobs:  
  deploy:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  
  
    - name: Set up Python  
      uses: actions/setup-python@v2  
      with:  
        python-version: '3.x'  
  
    - name: Install Databricks CLI  
      run: pip install --upgrade databricks-cli  
  
    - name: Deploy to Databricks  
      env:  
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}  
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  
      run: |  
        # Create the directory if it doesn't exist  
        databricks workspace mkdirs /Workspace/Users/michael.lotfy@skillsoft.com/DatabricksProject  
          
        # Import the app.py file to the workspace  
        databricks workspace import --language PYTHON app.py /Workspace/Users/michael.lotfy@skillsoft.com/DatabricksProject/app.py  
