name: Deploy to Databricks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI (new version)
      run: |
        curl -V
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        databricks -v

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN

#     - name: Deploy to Databricks  
#       env:  
#         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}  
#         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  
#       run: |  
#         # Create the directory if it doesn't exist  
#         databricks workspace mkdirs /Workspace/Users/michael.lotfy@skillsoft.com/newpr  
          
#         # Import the app.py file to the workspace  
# #        databricks workspace import --language PYTHON app.py /Workspace/Users/michael.lotfy@skillsoft.com/newpr/app.py 

#     - name: Sync Databricks App
#       run: |
# #        databricks apps sync --watch . /Workspace/Users/michael.lotfy@skillsoft.com/newpr/app.yaml
#          databricks apps deploy my-app-name --source-code-path /Workspace/Users/michael.lotfy@skillsoft.com/newpr/app01

    - name: Deploy Databricks App  
      run: |  
        databricks apps deploy chatbot --source-code-path /Workspace/Users/michael.lotfy@skillsoft.com/newpr  
